KitaplikMVC/Models/DTOs/BookCreateDto.cs
using KitaplikMVC_DAL.Concrete;
using System.ComponentModel.DataAnnotations;

namespace KitaplikMVC.Models.DTOs
{
    public class BookCreateDto
    {

        public int Id { get; set; }
        private DateTime _createDate = DateTime.UtcNow;

        public DateTime CreateDate
        {
            get { return _createDate; }
            set { _createDate = value; }
        }

        [Required(ErrorMessage = "Yazar Adı Alanı Mecburidir!")]
        [MaxLength(50)]
        public string Author { get; set; }

        [Required(ErrorMessage = "Fiyat Alanı Mecburidir!")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Kitap Adı Alanı Mecburidir!")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Kitap Türü Alanı Mecburidir!")]
        public Genre Genre { get; set; }

    }
}

KitaplikMVC/Models/DTOs/BookListDto.cs
using KitaplikMVC_DAL.Abstract;
using KitaplikMVC_DAL.Concrete;

namespace KitaplikMVC.Models.DTOs
{
    public class BookListDto
    {

        public int Id { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public string Title { get; set; }
        public Genre Genre { get; set; }
        public State State { get; set; }

    }
}

KitaplikMVC/Models/DTOs/BookUpdateDto.cs
using KitaplikMVC_DAL.Abstract;
using KitaplikMVC_DAL.Concrete;

namespace KitaplikMVC.Models.DTOs
{
    public class BookUpdateDto
    {

        public int Id { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public string Title { get; set; }
        public Genre Genre { get; set; }
        public State State { get; set; }

        private DateTime _updateDate = DateTime.UtcNow;

        public DateTime UpdateDate
        {
            get { return _updateDate; }
            set { _updateDate = value; }
        }

    }
}

KitaplikMVC/Models/ErrorViewModel.cs
namespace KitaplikMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KitaplikMVC/Controllers/AdminBookController.cs
using AutoMapper;
using KitaplikMVC.Models.DTOs;
using KitaplikMVC_DAL;
using KitaplikMVC_DAL.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace KitaplikMVC.Controllers
{
    public class AdminBookController : Controller
    {
        private readonly AdminDbContext context;
        private readonly IMapper mapper;

        public AdminBookController(AdminDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var BookList = context.Books.ToList();
            IList<BookListDto> books = mapper.Map<IList<BookListDto>>(BookList);

            return View(books);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var kitap = context.Books.FirstOrDefault(p => p.Id == id);
            BookUpdateDto updateDto = mapper.Map<BookUpdateDto>(kitap);

            return View(updateDto);
        }

        [HttpPost]
        public IActionResult Update(BookUpdateDto input)
        {
            if (!ModelState.IsValid) return View(input);
            Book book = mapper.Map<Book>(input);

            context.Books.Update(book);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            BookCreateDto updateDto = new();

            return View(updateDto);
        }

        [HttpPost]
        public IActionResult Create(BookCreateDto input)
        {
            if (ModelState.IsValid)
            {
                Book book = mapper.Map<Book>(input);
                context.Add(book);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(input);
        }

    }
}

KitaplikMVC/Controllers/BookController.cs
using AutoMapper;
using KitaplikMVC.Models.DTOs;
using KitaplikMVC_DAL;
using KitaplikMVC_DAL.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace KitaplikMVC.Controllers
{
    public class BookController : Controller
    {
        private readonly SqlDbContext context;
        private readonly IMapper mapper;

        public BookController(SqlDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var BookList = context.Books.ToList();
            IList<BookListDto> books = mapper.Map<IList<BookListDto>>(BookList);

            return View(books);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var kitap = context.Books.FirstOrDefault(p => p.Id == id);
            BookUpdateDto updateDto = mapper.Map<BookUpdateDto>(kitap);

            return View(updateDto);
        }

        [HttpPost]
        public IActionResult Update(BookUpdateDto input)
        {
            if (!ModelState.IsValid) return View(input);
            Book book = mapper.Map<Book>(input);

            context.Books.Update(book);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            BookCreateDto updateDto = new();

            return View(updateDto);
        }

        [HttpPost]
        public IActionResult Create(BookCreateDto input)
        {
            if (ModelState.IsValid)
            {
                Book book = mapper.Map<Book>(input);
                context.Add(book);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(input);
        }

    }
}

KitaplikMVC/Controllers/HomeController.cs
using KitaplikMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KitaplikMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KitaplikMVC/Views/AdminBook/Create.cshtml
@using KitaplikMVC.Models.DTOs
@model BookCreateDto

<div class="row">
    <form asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />

        <div class="form-group">
            <label asp-for="Title" class="control-label">Kitap Adı</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Author" class="control-label">Yazar Adı</label>
            <input asp-for="Author" class="form-control" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>

        @{
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "Bilim Kurgu",
                Value = "0"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Korku",
                Value = "1"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Romantik",
                Value = "2"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Kişisel Gelişim",
                Value = "3"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Tarih",
                Value = "4"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Din",
                Value = "5"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Psikoloji",
                Value = "6"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Ekonomi",
                Value = "7"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Felsefe",
                Value = "8"
            });
        }

        <div class="form-group">
            <label asp-for="Genre" class="control-label">Tür</label>
            @*@Html.DropDownList("Kitap Türü", listItems, new {@class = "form-control"})*@
            @Html.DropDownListFor(m => m.Genre, listItems, new {@class = "form-control"})
            <span asp-validation-for="Genre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="control-label">Fiyat</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        <br />

        <input type="submit" class="btn btn-success" value="Kaydet" />
        <input type="submit" class="btn btn-primary" value="Listeye Geri Dön" asp-action="Index" />

    </form>
</div>

KitaplikMVC/Views/AdminBook/Index.cshtml
@using KitaplikMVC.Models.DTOs
@model ICollection<BookListDto>

<a class="btn btn-primary" asp-controller="AdminBook" asp-action="Create">Yeni Kayıt</a>

<table class="table table-hover"> 
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Genre</th>
            <th>Price</th>
            <th>State</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>@item.Author</td>
                <td>@item.Genre</td>
                <td>@item.Price₺</td>
                <td>@item.State</td>

                <td>
                    @*<a class="btn btn-danger"
                    asp-action="Delete"
                    asp-controller="AdminBook"
                    asp-route-id="@item.Id">Sil</a>*@

                    <a class="btn btn-success"
                    asp-action="Update"
                    asp-controller="AdminBook"
                    asp-route-id="@item.Id">Güncelle</a>
                </td>

            </tr>
        }
    </tbody>
</table>

KitaplikMVC/Views/AdminBook/Update.cshtml
@using KitaplikMVC.Models.DTOs
@using System.Linq.Expressions
@model BookUpdateDto

<div class="row">
    <form asp-action="Update" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />

        <div class="form-group">
            <label asp-for="Title" class="control-label">Kitap Adı</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Author" class="control-label">Yazar Adı</label>
            <input asp-for="Author" class="form-control" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>

        @{
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "Bilim Kurgu",
                Value = "0"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Korku",
                Value = "1"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Romantik",
                Value = "2"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Kişisel Gelişim",
                Value = "3"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Tarih",
                Value = "4"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Din",
                Value = "5"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Psikoloji",
                Value = "6"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Ekonomi",
                Value = "7"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Felsefe",
                Value = "8"
            });
        }

        <div class="form-group">
            <label asp-for="Genre" class="control-label">Tür</label>
            @*@Html.DropDownList("Kitap Türü", listItems, new {@class = "form-control"})*@
            @Html.DropDownListFor(m => m.Genre, listItems, new {@class = "form-control"})
            <span asp-validation-for="Genre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="control-label">Fiyat</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        @{
            List<SelectListItem> listItemsState = new List<SelectListItem>();
            listItemsState.Add(new SelectListItem
            {
                Text = "Aktif",
                Value = "0"
            });
            listItemsState.Add(new SelectListItem
            {
                Text = "Pasif",
                Value = "1"
            });
        }

        <div class="form-group">
            <label asp-for="State" class="control-label">Durum</label>
            @Html.DropDownListFor(m => m.State, listItemsState, new {@class = "form-control"})
            <span asp-validation-for="State" class="text-danger"></span>
        </div>

        <br />

        <input type="submit" class="btn btn-success" value="Kaydet" />
        <input type="submit" class="btn btn-primary" value="Listeye Geri Dön" asp-action="Index" />

    </form>
</div>

KitaplikMVC/Views/Book/Create.cshtml
@using KitaplikMVC.Models.DTOs
@model BookCreateDto

<div class="row">
    <form asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />

        <div class="form-group">
            <label asp-for="Title" class="control-label">Kitap Adı</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Author" class="control-label">Yazar Adı</label>
            <input asp-for="Author" class="form-control" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>

        @{
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "Bilim Kurgu",
                Value = "0"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Korku",
                Value = "1"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Romantik",
                Value = "2"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Kişisel Gelişim",
                Value = "3"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Tarih",
                Value = "4"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Din",
                Value = "5"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Psikoloji",
                Value = "6"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Ekonomi",
                Value = "7"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Felsefe",
                Value = "8"
            });
        }

        <div class="form-group">
            <label asp-for="Genre" class="control-label">Tür</label>
            @*@Html.DropDownList("Kitap Türü", listItems, new {@class = "form-control"})*@
            @Html.DropDownListFor(m => m.Genre, listItems, new {@class = "form-control"})
            <span asp-validation-for="Genre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="control-label">Fiyat</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        <br />

        <input type="submit" class="btn btn-success" value="Kaydet" />
        <input type="submit" class="btn btn-primary" value="Listeye Geri Dön" asp-action="Index" />

    </form>
</div>

KitaplikMVC/Views/Book/Index.cshtml
@using KitaplikMVC.Models.DTOs
@model ICollection<BookListDto>

<a class="btn btn-primary" asp-controller="Book" asp-action="Create">Yeni Kayıt</a>

<table class="table table-hover"> 
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Genre</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>@item.Author</td>
                <td>@item.Genre</td>
                <td>@item.Price₺</td>

                <td>
                    @*<a class="btn btn-danger"
                    asp-action="Delete"
                    asp-controller="Book"
                    asp-route-id="@item.Id">Sil</a>*@

                    <a class="btn btn-success"
                    asp-action="Update"
                    asp-controller="Book"
                    asp-route-id="@item.Id">Güncelle</a>
                </td>

            </tr>
        }
    </tbody>
</table>

KitaplikMVC/Views/Book/Update.cshtml
@using KitaplikMVC.Models.DTOs
@using System.Linq.Expressions
@model BookUpdateDto

<div class="row">
    <form asp-action="Update" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />

        <div class="form-group">
            <label asp-for="Title" class="control-label">Kitap Adı</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Author" class="control-label">Yazar Adı</label>
            <input asp-for="Author" class="form-control" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>

        @{
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "Bilim Kurgu",
                Value = "0"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Korku",
                Value = "1"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Romantik",
                Value = "2"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Kişisel Gelişim",
                Value = "3"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Tarih",
                Value = "4"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Din",
                Value = "5"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Psikoloji",
                Value = "6"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Ekonomi",
                Value = "7"
            });
            listItems.Add(new SelectListItem
            {
                Text = "Felsefe",
                Value = "8"
            });
        }

        <div class="form-group">
            <label asp-for="Genre" class="control-label">Tür</label>
            @*@Html.DropDownList("Kitap Türü", listItems, new {@class = "form-control"})*@
            @Html.DropDownListFor(m => m.Genre, listItems, new {@class = "form-control"})
            <span asp-validation-for="Genre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="control-label">Fiyat</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        @{
            List<SelectListItem> listItemsState = new List<SelectListItem>();
            listItemsState.Add(new SelectListItem
            {
                Text = "Aktif",
                Value = "0"
            });
            listItemsState.Add(new SelectListItem
            {
                Text = "Pasif",
                Value = "1"
            });
        }

        <div class="form-group">
            <label asp-for="State" class="control-label">Durum</label>
            @Html.DropDownListFor(m => m.State, listItemsState, new {@class = "form-control"})
            <span asp-validation-for="State" class="text-danger"></span>
        </div>

        <br />

        <input type="submit" class="btn btn-success" value="Kaydet" />
        <input type="submit" class="btn btn-primary" value="Listeye Geri Dön" asp-action="Index" />

    </form>
</div>

KitaplikMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KitaplikMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KitaplikMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KitaplikMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminBook" asp-action="Index">[Admin]Book Stock</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">[Customer]Book Stock</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - KitaplikMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>